---
title: "Zadanie domowe 2"
output: html_document
---

Eksperymenty
-----------

Definiuję funkcję tworzącą próbkę z rozkładu różnic średnich dla grup o równych licznościach
k - liczba grup,
l - liczność grup

```{r}
f<-function(k, l) {
  x<-rnorm(k*l)
  g<-rep(1:k,times=l)
  y<-tapply(x, g, mean)
  roznica<-max(y)-min(y)
  return(roznica)
}
```
Definiuję funkcję tworzącą próbkę z rozkładu różnic średnich dla grup o różnych licznościach
k - liczba grup
l - średnia liczność grup
p - wektor k-elementowy prawodobieństw przynależności do każdej z grup

```{r}
g<-function(k, l, p) {
  x<-rnorm(k*l)
  i<-sample(1:k, size=k*l, prob=p, replace=TRUE)
  y<-tapply(x, i, mean)
  roznica<-max(y)-min(y)
  return(roznica)
}
```
Wykonuję serię eksperymentów porównującą rozkłady różnic średnich w obu przypadkach

1. Podział na 4 grupy, każda średnio po 100 elementów

```{r}
n<-10000
k<-4
l<-100
A<-replicate(n, f(k, l))
B<-replicate(n, g(k, l, c(0.1, 0.5, 0.3, 0.1)))
ks.test(A,B)
```

Uzyskana p-wartość sugeruje, że rozkłady są istonie różne (dla poziomu istotności 0.05).

2. Podział na 20 grup, każda średnio po 100 elementów

```{r}
n<-10000
k<-20
l<-100
A<-replicate(n, f(k, l))
B<-replicate(n, g(k, l, c(0.01, 0.08, 0.05, 0.05, 0.04, 0.03, 0.1, 0.06, 0.08, 0.03, 0.06, 0.07, 0.01, 0.03, 0.03, 0.01, 0.08, 0.09, 0.06, 0.03)))
ks.test(A,B)
```

Uzyskana p-wartość sugeruje, że rozkłady są istonie różne (dla poziomu istotności 0.05).

3. Podział na 5 grup, każda średnio po 20 elementów

```{r}
n<-10000
k<-5
l<-20
A<-replicate(n, f(k, l))
B<-replicate(n, g(k, l, c(0.2, 0.2, 0.2, 0.2, 0.2)))
ks.test(A,B)
```


Pomimo tego, że prawdopodobieństwa wystąpienia każdej z grup są równe, uzyskana p-wartość sugeruje, że rozkłady są istonie różne (dla poziomu istotności 0.05). 

Wnioski
--------

Na podstawie powyższych symulacji można stwierdzić, że rozkład różnic średnich w przypadku zbalansowanym różni się od rozkładu różnic średnich dla przypadku niezbalansowanego. Oznacza to, że testów SNK/HSD nie można stosować w przypadku niezbalansowanym.
