---
title: "PD2"
author: "Marta Pałuba"
date: "Modele liniowe i mieszane"
output: 
  html_document:
  toc: TRUE
---
Generuję próbkę z czteremia grupami równoelementowymi:

```{r}
wektor1=replicate(10000, {
  wyniki <- rnorm(400, 0,1)
  grupy <- rep(c("a","b","c","d"),100)
  srednie<-tapply(wyniki,grupy,mean)
  max(srednie)-min(srednie)
})
```

Generuję próbjkę z czterema grupami różnoelementowymi

```{r}
wektor2=replicate(10000, {
  wyniki <- rnorm(400, 0,1)
  grupy <- rep(c("a","b","c","d"),c(150,50,75,125))
  srednie<-tapply(wyniki,grupy,mean)
  max(srednie)-min(srednie)
})
```

Przeprwadzam na nich dwóch test Kołmogorowa-Smirnowa:

```{r}
ks.test(wektor1,wektor2)
```

Jak widzimy, rozkłady te nie są takie same.

Generuję próbkę z sześcioma grupami różnoelementowymi i porównuję rozkłądy z poprzednimi dwoma:
```{r}
wektor3=replicate(10000, {
  wyniki <- rnorm(400, 0,1)
  grupy <- rep(c("a","b","c","d","e","f"),c(38,12,170,16,55,109))
  srednie<-tapply(wyniki,grupy,mean)
  max(srednie)-min(srednie)
})
ks.test(wektor1,wektor3)
ks.test(wektor2,wektor3)
```
Widać, że rozkłady są różne.